
services:
  - type: web
    name: telegram-finance-bot
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
    envVars:
      - key: TOKEN
        value: your-telegram-bot-token
